import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import SmoothScrollProvider from "@/components/client/smooth-scroll-provider";
import "./globals.css";
import Navbar from "@/components/client/navbar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "PRESSIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <Navbar/>
        <SmoothScrollProvider>{children}
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
